<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$partner=[];
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner=$helper->getSeller();
$isPartner = $helper->isSeller();
if ($isPartner == 1) {
    $others_info=$partner['others_info'];
    ?>
    <form action="<?= $block->escapeUrl($block->getUrl('marketplace/order/printpdfinfo', ['_secure' => $this->getRequest()->isSecure()])) ?>" enctype="multipart/form-data" method="post" id="form-selleraddress-validate">
        <?= $block->getBlockHtml('formkey')?>
        <?= $block->getBlockHtml('seller.formkey')?>
        <div class="wk-mp-design">
            <fieldset class="fieldset info">
                <legend class="legend"><span><?= /* @noEscape */ __('Invoice and Packing Slip Address/VAT/Tax Information') ?></span></legend>
                <div class="field">
                    <div class="control">
                        <textarea class="input-text" name="others_info" title="Address/VAT/Tax Information" cols="1" rows="3" ><?= $block->escapeHtml($others_info); ?></textarea>
                    </div>
                </div>
                <div class="field">
                    <button class="button wk_mp_btn" title="<?= /* @noEscape */ __('Save Payment') ?>" type="submit" id="savepaym">
                        <span><span><?= /* @noEscape */ __('Save Information') ?></span></span>
                    </button>
                </div>
            </fieldset>
        </div>
    </form>
    <?php
} else { ?>
    <h2 class="wk_mp_error_msg">
        <?= /* @noEscape */ __("To Become Seller Please Contact to Admin."); ?>
    </h2>
    <?php
} ?>
