<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<img src="<?= $block->escapeUrl($block->getSellerStatisticsGraphUrl(true)) ?>" alt="<?= /* @noEscape */ __('Top Selling Country'); ?>" title="<?= /* @noEscape */ __('Top Selling Country'); ?>" id="wk-location-chart"/>
