<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
if ($block->isShippineAvlForSeller()) { ?>
    <li data-ui-id="menu-webkul-marketplace-shipsetting-menu" class="item-menu parent level-1">
        <strong class="wk-mp-submenu-group-title">
            <span><?= /* @noEscape */ __('Shipping Settings')?></span>
        </strong>
        <div class="wk-mp-submenu">
            <ul>
                <?= $block->getChildHtml();?>
            </ul>
        </div>
    </li>
<?php } ?>
