<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
    $partner = $block->getProfileDetail();
?>
<?php if (!empty($partner['shop_url'])): ?>
    <div class="wk-mp-design">
        <?= $this->getChildHtml();?>
    </div>
<?php endif; ?>
